---
title: "Resultados_redes_reales"
author: "LeonardoClaudin"
date: "17/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(ggplot2)
```

##------------------------------------------------------------------------------

```{r}
CCoef_chumberas <- read.csv("Your Results of Clustering Coefficient in Chumberas", sep = ";")
CCoef_alcornoques <- read.csv("Your Results of Clustering Coefficient in Alcornoques", sep = ";")
CCoef_viñedos <- read.csv("Your Results of Clustering Coefficient in Viñedos", sep = ";")
CCoef_olivos <- read.csv("Your Results of Clustering Coefficient in Olivos", sep = ";")
```

```{r}
CCoef_chumberas$Class <- "chumberas"
CCoef_alcornoques$Class <- "alcornoques"
CCoef_olivos$Class <- "olivos"
CCoef_viñedos$Class <- "viñedos"

Clustering.coef <- rbind(CCoef_chumberas, CCoef_alcornoques, CCoef_olivos, CCoef_viñedos)
Clustering.coef$Size <- ordered(Clustering.coef$Size, levels = c(100, 500, 1000, 1500, 2000))
```

```{r}
pdf("Clustering_redes_reales.pdf", 12, 10)
ggplot(Clustering.coef, aes(x = R, y = Cluster)) + geom_point(aes(color = as.factor(Size)), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Tamaño muestral (M)") + xlab("Distancia umbral (R)") + 
  ylab("Coeficiente de Clustering (C)") +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "bottom",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1")) + ylim(0,1)
dev.off()
```

```{r}
pdf("Clustering_radio_redes_reales.pdf", 12, 10)
ggplot(Clustering.coef, aes(x = Size, y = Cluster)) + geom_point(aes(color = R), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Umbral (R)") + xlab("Tamaño Muestral (M)") + 
  ylab("Coeficiente de Clustering (C)") +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "right",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1"))+ ylim(0,1)
dev.off()
```

##------------------------------------------------------------------------------

```{r}
Mod_chumberas <- read.csv("Your Results of Modularity in Chumberas", sep = ";")
Mod_alcornoques <- read.csv("Your Results of Modularity in Alcornoques", sep = ";")
Mod_viñedos <- read.csv("Your Results of Modularity in Viñedos", sep = ";")
Mod_olivos <- read.csv("Your Results of Modularity in Olivos", sep = ";")
```

```{r}
Mod_chumberas$Class <- "chumberas"
Mod_alcornoques$Class <- "alcornoques"
Mod_olivos$Class <- "olivos"
Mod_viñedos$Class <- "viñedos"

Modularidad <- rbind(Mod_chumberas, Mod_alcornoques, Mod_olivos, Mod_viñedos)
Modularidad$Size <- ordered(Modularidad$Size, levels = c(100, 500, 1000, 1500, 2000))
```

```{r}
pdf("Modularidad.pdf", 12, 10)
ggplot(Modularidad, aes(x = R, y = Mod)) + geom_point(aes(color = as.factor(Size)), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Tamaño muestral (M)") + xlab("Distancia umbral (R)") + 
  ylab("Modularidad (Q)") +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "bottom",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1")) + ylim(0,1)
dev.off()
```
```{r}
pdf("Modularidad_radio_redes_reales.pdf", 12, 10)
ggplot(Modularidad, aes(x = Size, y = Mod)) + geom_point(aes(color = R), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Umbral (R)") + xlab("Tamaño Muestral (M)") + 
  ylab("Modularidad (Q)") +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "right",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1")) + ylim(0,1)
dev.off()
```


##------------------------------------------------------------------------------

```{r}
Diam_chumberas <- read.csv("Your Results of Diameter in Chumberas", sep = ";")
Diam_alcornoques <- read.csv("Your Results of Diameter in Alcornoques", sep = ";")
Diam_viñedos <- read.csv("Your Results of Diameter in Viñedos", sep = ";")
Diam_olivos <- read.csv("Your Results of Diameter in Olivos", sep = ";")
```

```{r}
Diam_chumberas$Class <- "chumberas"
Diam_alcornoques$Class <- "alcornoques"
Diam_olivos$Class <- "olivos"
Diam_viñedos$Class <- "viñedos"
Diámetro <- rbind(Diam_chumberas, Diam_alcornoques, Diam_olivos, Diam_viñedos)
Diámetro$Size <- ordered(Diámetro$Size, levels = c(100, 500, 1000, 1500, 2000))
```

```{r}
pdf("Diámetro.pdf", 12, 10)
ggplot(Diámetro, aes(x = R, y = Diametro)) + geom_point(aes(color = as.factor(Size)), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Tamaño muestral (M)") + xlab("Distancia umbral (R)") + 
  ylab("Diámetro (D)") +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "bottom",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1"))
dev.off()
```

```{r}
pdf("Diámetro_radio_redes_reales.pdf", 12, 10)
ggplot(Diámetro, aes(x = Size, y = Diametro)) + geom_point(aes(color = R), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Umbral (R)") + xlab("Tamaño Muestral (M)") + 
  ylab("Diámetro (D)") +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "right",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1"))
dev.off()
```

```{r}
EdgeD_chumberas <- read.csv("Your Results of Degree Connection in Chumberas", sep = ";")
EdgeD_alcornoques <- read.csv("Your Results of Degree Connection in Alcornoques", sep = ";")
EdgeD_viñedos <- read.csv("Your Results of Degree Connection in Viñedos", sep = ";")
EdgeD_olivos <- read.csv("Your Results of Degree Connection in Olivos", sep = ";")
```

```{r}
EdgeD_chumberas$Class <- "chumberas"
EdgeD_alcornoques$Class <- "alcornoques"
EdgeD_olivos$Class <- "olivos"
EdgeD_viñedos$Class <- "viñedos"
Densidad.conexiones <- rbind(EdgeD_chumberas, EdgeD_alcornoques, EdgeD_olivos, EdgeD_viñedos)
Densidad.conexiones$Size <- ordered(Densidad.conexiones$Size, levels =c(100, 500, 1000, 1500, 2000))
```

```{r}
pdf("EdgeD.pdf", 12, 10)
ggplot(Densidad.conexiones, aes(x = R, y = EdgeD)) + geom_point(aes(color = as.factor(Size)), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Tamaño muestral (M)") + xlab("Distancia umbral (R)") + 
  ylab("Densidad de conexiones") +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "bottom",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1")) + ylim(0,1)
dev.off()
```
```{r}
pdf("EdgeD_radio_redes_reales.pdf", 12, 10)
ggplot(Densidad.conexiones, aes(x = Size, y = EdgeD)) + geom_point(aes(color = R), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Umbral (R)") + xlab("Tamaño Muestral (M)") + 
  ylab("Densidad de Conexiones") +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "right",
        strip.text = element_text(size=16, color = "black"),
        strip.background =element_rect(fill="slategray1")) + ylim(0,1)
dev.off()
```


```{r}
LCC_chumberas <- read.csv("Your Results of Giant Component in Chumberas", sep = ";")
LCC_alcornoques <- read.csv("Your Results of Giant Component in Alcornoques", sep = ";")
LCC_viñedos <- read.csv("Your Results of Giant Component in Viñedos", sep = ";")
LCC_olivos <- read.csv("Your Results of Giant Component in Olivos", sep = ";")
```

```{r}
LCC_chumberas$Class <- "chumberas"
LCC_alcornoques$Class <- "alcornoques"
LCC_olivos$Class <- "olivos"
LCC_viñedos$Class <- "viñedos"
Componente.gigante <- rbind(LCC_chumberas, LCC_alcornoques, LCC_olivos, LCC_viñedos)
Componente.gigante$Size <- ordered(Componente.gigante$Size, levels = c(100, 500, 1000, 1500, 2000))
```

```{r}
pdf("LCC_redes_reales.pdf", 12, 10)
ggplot(Componente.gigante, aes(x = R, y = LCC)) + geom_point(aes(color = as.factor(Size)), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Tamaño muestral (M)") + xlab("Distancia umbral (R)") + 
  ylab("Componente Conexa Mayor (LCC)") +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        legend.position = "bottom",
        strip.text = element_text(size=16, color = "black"),
        strip.background = element_rect(fill="slategray1")) 
dev.off()
```

```{r}
pdf("LCC_radio_redes_reales.pdf", 12, 10)
ggplot(Componente.gigante, aes(x = Size, y = LCC)) + geom_point(aes(color = R), position = "jitter") +
  facet_wrap(.~Class, nrow = 2) + labs(color = "Umbral (R)") + xlab("Tamaño muestral (M)") + 
  ylab("Componente Conexa Mayor (LCC)") +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(axis.text=element_text(size=16), 
        axis.title=element_text(size=16),
        legend.position = "right",
        panel.background = element_rect(fill = "white", colour = "slategray2", size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "slategray1"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "slategray1"),
        strip.text = element_text(size=16, color = "black"),
        strip.background = element_rect(fill="slategray1"))
dev.off()
```




